/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-14 16:13:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.lang.*;
import java.util.*;
import java.text.*;
import java.net.*;

public final class service_005fnotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1610638345172L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1610540369989L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>OO펜션 - 예약안내</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/common.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("\t.content {width: 100%; height: 90vh;}\r\n");
      out.write("\t.roomInfo {border: 1px solid #e1bee7; margin: 0 auto; width: 90%; margin-top: 5%;}\r\n");
      out.write("\t.roomInfo th { background-color: rgb(255,190,231); width: 14%; height: 35px; border: 1px solid #e1bee7;}\r\n");
      out.write("\t.roomInfo td {text-align: center; border: 1px solid #e1bee7;}\r\n");
      out.write("\t.roomInfo td:first-child {font-weight: bold; height: 30px;}\r\n");
      out.write("\t.content ul {width: 90%; margin: 0 auto; }\r\n");
      out.write("\t.content ul li:first-child {font-weight: bold; font-size: 22px; border-bottom: 3px solid #ddd; margin-top: 10px; margin-bottom: 10px; list-style: none; margin-left: 0;}\r\n");
      out.write("\t.seasonInfo li, .pensionInfo li {list-style: square; margin-left: 40px; margin-bottom: 5px;}\r\n");
      out.write("\t.seasonInfo, .pensionInfo, .refundInfo {padding-top: 50px;}\r\n");
      out.write("\t\r\n");
      out.write("\t.refundInfo_tbl {border: 1px solid #e1bee7; margin: 0 auto; width: 90%;}\r\n");
      out.write("\t.refundInfo_tbl th { background-color: rgb(255,190,231); width: 14%; height: 35px; border: 1px solid #e1bee7;}\r\n");
      out.write("\t.refundInfo_tbl td {text-align: center; border: 1px solid #e1bee7;}\r\n");
      out.write("\t.refundInfo_tbl td:first-child {font-weight: bold; height: 30px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div class=\"hd_wrap\">\r\n");
      out.write("                <a href=\"index\" class=\"logo\"><img src=\"resources/img/O_fine_logo.png\" alt=\"로고\"></a>\r\n");
      out.write("                <nav class=\"gnb\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"about\">ABOUT</a></li>\r\n");
      out.write("                        <li><a href=\"room_list\">ROOMS</a></li>\r\n");
      out.write("                        <li><a href=\"facility\">FACILITY</a></li>\r\n");
      out.write("                        <li><a href=\"service\">SERVICE</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div class=\"login_box\">\r\n");
      out.write("                    <a href=\"login\">로그인</a>\r\n");
      out.write("                    <a href=\"mem_join\">회원가입</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<table class=\"roomInfo\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>객실명</th>\r\n");
      out.write("\t\t\t\t<th>형태</th>\r\n");
      out.write("\t\t\t\t<th>평수</th>\r\n");
      out.write("\t\t\t\t<th>기준인원/최대인원</th>\r\n");
      out.write("\t\t\t\t<th>평일(일~목)</th>\r\n");
      out.write("\t\t\t\t<th>주말(금~토/공휴일 전일)</th>\r\n");
      out.write("\t\t\t\t<th>성수기 / 준성수기</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>A-101</td>\r\n");
      out.write("\t\t\t\t<td>복층/침대</td>\r\n");
      out.write("\t\t\t\t<td>15평(49.5m2)</td>\r\n");
      out.write("\t\t\t\t<td>2명/3명</td>\r\n");
      out.write("\t\t\t\t<td>30,000원</td>\r\n");
      out.write("\t\t\t\t<td>200,000원</td>\r\n");
      out.write("\t\t\t\t<td>전화문의</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>A-102</td>\r\n");
      out.write("\t\t\t\t<td>침대</td>\r\n");
      out.write("\t\t\t\t<td>15평(49.5m2)</td>\r\n");
      out.write("\t\t\t\t<td>2명/3명</td>\r\n");
      out.write("\t\t\t\t<td>30,000원</td>\r\n");
      out.write("\t\t\t\t<td>200,000원</td>\r\n");
      out.write("\t\t\t\t<td>전화문의</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>B-101</td>\r\n");
      out.write("\t\t\t\t<td>복층/온돌</td>\r\n");
      out.write("\t\t\t\t<td>20평(66.1m2)</td>\r\n");
      out.write("\t\t\t\t<td>2명/4명</td>\r\n");
      out.write("\t\t\t\t<td>50,000원</td>\r\n");
      out.write("\t\t\t\t<td>270,000원</td>\r\n");
      out.write("\t\t\t\t<td>전화문의</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<ul class=\"seasonInfo\">\r\n");
      out.write("\t\t<li>기간안내</li>\r\n");
      out.write("\t\t<li>성수기 : 7월20일 ~ 8월 20일</li>\r\n");
      out.write("\t\t<li>준성수기 : 7월1일 ~ 19일 / 8월21일 ~ 31일</li>\r\n");
      out.write("\t\t<li>비수기 : 그외 모든 날짜</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"pensionInfo\">\r\n");
      out.write("\t\t<li>펜션안내</li>\r\n");
      out.write("\t\t<li>입/퇴실시간 : (입실) 14시부터 / (퇴실) 퇴실일 오전 11시까지 </li>\r\n");
      out.write("\t\t<li>이용규칙 : 객실 키카드 보증금 3만원 및 퇴실시 분실,파손된 물품에 따라 추가비용이 발생할 수 있습니다.</li>\r\n");
      out.write("\t\t<li>이용규칙(2) : 객실내 취사는 가능하오나 연기 혹은 냄새가 많이나는 음식은 조리하실 수 없습니다.</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<ul class=\"refundInfo\">\r\n");
      out.write("\t\t<li>환불규정</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<table class=\"refundInfo_tbl\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>날짜(이용일 기준)</th>\r\n");
      out.write("\t\t\t\t<th>이용 당일</th>\r\n");
      out.write("\t\t\t\t<th>이용 1일전</th>\r\n");
      out.write("\t\t\t\t<th>이용 2일전</th>\r\n");
      out.write("\t\t\t\t<th>이용 3일전</th>\r\n");
      out.write("\t\t\t\t<th>이용 4일전</th>\r\n");
      out.write("\t\t\t\t<th>이용 5일전</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>취소수수료(%)</td>\r\n");
      out.write("\t\t\t\t<td>100%</td>\r\n");
      out.write("\t\t\t\t<td>90%</td>\r\n");
      out.write("\t\t\t\t<td>80%</td>\r\n");
      out.write("\t\t\t\t<td>70%</td>\r\n");
      out.write("\t\t\t\t<td>50%</td>\r\n");
      out.write("\t\t\t\t<td>0%</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"ft_wrap\">\r\n");
      out.write("                <ul class=\"ft_info_box\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h4 class=\"ft_info_tit\">ABOUT</h4>\r\n");
      out.write("                        <p>등록명 : 화인스톤펜션</p>\r\n");
      out.write("                        <p>대표자 : 서지원</p>\r\n");
      out.write("                        <p>주소 : 경기도 가평시 OO리 123-1</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h4 class=\"ft_info_tit\">CONTACT US</h4>\r\n");
      out.write("                        <p>HP : 010-1234-1234</p>\r\n");
      out.write("                        <p>TEL : 031-0000-0000</p>\r\n");
      out.write("                        <p>E-MAIL : OOOOOO@naver.com</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <h4 class=\"ft_info_tit\">BANK INFO</h4>\r\n");
      out.write("                        <p>계좌번호 : 12345-123-123456 <br>\r\n");
      out.write("                            OO은행 </p>\r\n");
      out.write("                        <p>예금주 : OOO</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>    \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
